version: "3.8"
services:
  BloomDiscordBot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bloomgamestudio/bloomdiscordbot:main
    restart: unless-stopped
    volumes:
      - bloomdiscordbotvolume:/app/data
      - configvolume:/app/config
    env_file:
      - .env

volumes:
  bloomdiscordbotvolume: {}
  configvolume: {}