version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bloomgamestudio/bloomdiscordbot:main
    restart: unless-stopped
    env_file: .env
    volumes:
      - data:/main

volumes:
  data:
